"""Agente: DREAD Validator — Fase III.5: Validación de severidad.

Revisa los threats finales producidos por el Threat Synthesizer y
valida/ajusta los DREAD scores usando un análisis profundo del
sistema, considerando:
  - El contexto original del usuario (prompt + archivos)
  - La arquitectura parseada
  - Los reportes de todas las metodologías
  - El debate Red/Blue
  - El enriched attack tree

Este es un agente Deep Thinker — usa el modelo más capaz.
"""

from __future__ import annotations

import concurrent.futures
import json
import logging
import time
from typing import TYPE_CHECKING

from agentictm.agents.base import invoke_agent, extract_json_from_response
from agentictm.rag.tools import VALIDATOR_TOOLS
from agentictm.state import ThreatModelState

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel
    from agentictm.config import AgenticTMConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System Prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a senior security risk analyst specializing in DREAD risk scoring
validation. Your job is to review a list of threats that were generated by
multiple AI agents and ensure that each threat's DREAD scores accurately
reflect the REAL impact on the specific system being analyzed.

## Your responsibilities:

1. **Review each threat** against the actual system architecture and context
2. **Validate DREAD scores** (each dimension 1-10):
   - **D**amage: How bad is it if the attack succeeds?
   - **R**eproducibility: How easy is it to reproduce the attack?
   - **E**xploitability: How much effort/skill is needed? (10=trivial, 1=nation-state)
   - **A**ffected Users: How many users/systems are impacted?
   - **D**iscoverability: How easy is it to discover the vulnerability?
3. **Adjust scores** — deflate over-scored threats, raise under-scored ones
4. **Ensure consistency** across threats — similar severity should have similar scores
5. **Recalculate priorities** based on corrected DREAD totals (avg = total / 5):
   - Critical: avg >= 9.0 (total >= 45) — RARE, max 2-3 per model
   - High: avg >= 7.0 (total >= 35)
   - Medium: avg >= 4.0 (total >= 20)
   - Low: avg < 4.0 (total < 20)
6. **DO NOT add new threats.** Your ONLY job is to validate and adjust scores
   for the threats you receive. Output EXACTLY the same threat IDs you were given.
7. **DO NOT merge or remove threats.** Every input threat MUST appear in your
   output with its original ID. Adjust scores only — never drop, merge, or create.

## CRITICAL SCORING RULES:
- Each dimension MUST have a DIFFERENT value. Uniform scores (e.g. 8/8/8/8/8)
  are NEVER acceptable. Real vulnerabilities have varying impact across dimensions.
- Example of GOOD scoring: D=7, R=5, E=4, A=8, D=3 (total=27, avg=5.4, Medium)
- Example of BAD scoring: D=8, R=8, E=8, A=8, D=8 (REJECTED — too uniform)
- A typical well-scoped threat model has: 0-2 Critical, 3-6 High, 5-10 Medium, 2-5 Low.
  If the input has many Critical threats, your primary job is to DEFLATE them.

## IMPORTANT guidelines:
- Be REALISTIC, not paranoid. Score based on the SPECIFIC system, not generic worst-case
- Consider the system's actual trust boundaries and data sensitivity
- A web app with no PII has lower Affected Users than a healthcare system
- API-only systems without a public frontend have lower Discoverability
- Systems behind VPNs or internal networks have lower Exploitability
- Complex multi-step attacks → lower Reproducibility (2-4)
- DO NOT inflate scores just to seem thorough. Accuracy > quantity.
- When in doubt, score LOWER. Security teams lose trust in models that cry wolf.

## Output format:
Respond with a JSON object:
```json
{
  "validation_notes": "Brief summary of what you changed and why",
  "threats": [
    {
      "id": "TM-001",
      "component": "Component name",
      "description": "Threat description",
      "methodology": "Source methodology(ies)",
      "stride_category": "S|T|R|I|D|E",
      "attack_path": "How the attack would be executed",
      "damage": 7,
      "reproducibility": 4,
      "exploitability": 5,
      "affected_users": 8,
      "discoverability": 3,
      "dread_total": 27,
      "priority": "Medium",
      "mitigation": "Recommended mitigation",
      "control_reference": "NIST/CIS/ISO control reference",
      "effort": "Low|Medium|High",
      "observations": "Validation notes for this specific threat",
      "status": "Open"
    }
  ]
}
```

SCORING CALIBRATION EXAMPLES — use these as reference:

Good (realistic, asymmetric):
  SQL Injection on public API:      D=9, R=7, E=6, A=8, D=5 → total=35, avg=7.0, High
  Missing rate limiting:            D=4, R=9, E=8, A=6, D=7 → total=34, avg=6.8, Medium
  Weak password policy:             D=6, R=3, E=4, A=7, D=2 → total=22, avg=4.4, Medium
  Log injection via headers:        D=3, R=6, E=5, A=2, D=4 → total=20, avg=4.0, Medium
  Internal service without mTLS:    D=5, R=4, E=2, A=3, D=1 → total=15, avg=3.0, Low

Bad (lazy, inflated, unrealistic):
  D=8, R=8, E=8, A=8, D=8 → REJECTED (uniform is never real)
  D=5, R=5, E=5, A=5, D=5 → REJECTED (must differentiate dimensions)
  D=10,R=10,E=10,A=10,D=10 → REJECTED (nothing is maximum on all axes)
"""


def _build_human_prompt(state: ThreatModelState) -> str:
    """Build the human prompt with all context for DREAD validation."""
    # System description + architecture
    system_name = state.get("system_name", "System")
    system_desc = state.get("system_description", "")
    raw_input = state.get("raw_input", "")
    components = state.get("components", [])
    data_flows = state.get("data_flows", [])
    trust_boundaries = state.get("trust_boundaries", [])
    categories = state.get("threat_categories", [])
    threats_final = state.get("threats_final", [])
    methodology_reports = state.get("methodology_reports", [])

    # ── 1. System description ──
    sys_desc_text = system_desc or raw_input or "(no description available)"
    user_input_text = raw_input or system_desc or "(no raw input)"

    # ── 2. Architecture details ──
    def _fmt_component(c: object) -> str:
        if isinstance(c, dict):
            name = c.get("name", "?")
            ctype = c.get("type", "")
            desc = c.get("description", "")
            return f"  - {name} [{ctype}]" + (f": {desc}" if desc else "")
        return f"  - {c}"

    def _fmt_flow(f: object) -> str:
        if isinstance(f, dict):
            src = f.get("source", "?")
            dst = f.get("destination", "?")
            protocol = f.get("protocol", "")
            data = f.get("data", "")
            line = f"  - {src} → {dst}"
            if protocol:
                line += f" [{protocol}]"
            if data:
                line += f": {data}"
            return line
        return f"  - {f}"

    def _fmt_boundary(b: object) -> str:
        if isinstance(b, dict):
            name = b.get("name", "?")
            desc = b.get("description", "")
            inside = b.get("inside", [])
            line = f"  - {name}"
            if desc:
                line += f": {desc}"
            if inside:
                line += f" [contains: {', '.join(str(i) for i in inside)}]"
            return line
        return f"  - {b}"

    components_text = "\n".join(_fmt_component(c) for c in components) or "  (none)"
    flows_text = "\n".join(_fmt_flow(f) for f in data_flows) or "  (none)"
    boundaries_text = "\n".join(_fmt_boundary(b) for b in trust_boundaries) or "  (none)"

    # ── 3. Methodology reports — deduplicated ──
    seen_methodologies: set[str] = set()
    unique_reports: list[dict] = []
    for r in methodology_reports:
        mkey = r.get("methodology", "Unknown")
        if mkey in seen_methodologies:
            continue
        seen_methodologies.add(mkey)
        unique_reports.append(r)

    methodology_sections = ""
    attack_tree_sections = ""
    for r in unique_reports:
        methodology = r.get("methodology", "Unknown")
        agent_name = r.get("agent", "")
        report_text = r.get("report", "")
        threats_raw = r.get("threats_raw", [])

        if "ATTACK_TREE" in methodology.upper():
            attack_tree_sections += f"\n### {methodology}\n{report_text[:10000]}\n"
            if threats_raw:
                attack_tree_sections += f"\n**Threats from tree ({len(threats_raw)}):**\n"
                for tr in threats_raw[:40]:
                    comp = tr.get("component", "")
                    desc = tr.get("description", "")
                    attack_tree_sections += f"  - [{comp}] {desc}\n"
            continue

        methodology_sections += f"\n---\n### {methodology} (agent: {agent_name})\n"
        methodology_sections += f"**Report:**\n{report_text[:8000]}\n"
        if threats_raw:
            methodology_sections += f"\n**Raw threats identified ({len(threats_raw)}):**\n"
            for tr in threats_raw[:40]:
                tr_id = tr.get("id", "")
                tr_comp = tr.get("component", "")
                tr_stride = tr.get("stride_category", "")
                tr_desc = tr.get("description", "")
                tr_prio = tr.get("priority", "")
                line = f"  - {tr_id} [{tr_stride}] {tr_comp}: {tr_desc}"
                if tr_prio:
                    line += f" (priority: {tr_prio})"
                methodology_sections += line + "\n"

    # ── 4. Full debate history ──
    debate_history = state.get("debate_history", [])
    if debate_history:
        debate_text = f"Total rounds recorded: {len(debate_history)}\n\n"
        for entry in debate_history:
            if isinstance(entry, dict):
                side = entry.get("side", "?").upper()
                rnd = entry.get("round", "?")
                arg = entry.get("argument", "")
            else:
                side = getattr(entry, "side", "?").upper()
                rnd = getattr(entry, "round", "?")
                arg = getattr(entry, "argument", "")
            debate_text += f"**{side} TEAM — Round {rnd}:**\n{arg[:5000]}\n\n"
    else:
        debate_text = "No debate history available."

    # ── 5. Compact threat list — truncate descriptions to stay within context window ──
    compact_threats = []
    for t in threats_final:
        compact_threats.append({
            "id": t.get("id", ""),
            "component": t.get("component", "")[:80],
            "description": t.get("description", "")[:500],
            "methodology": t.get("methodology", ""),
            "stride_category": t.get("stride_category", ""),
            "attack_path": t.get("attack_path", "")[:400],
            "damage": t.get("damage", 0),
            "reproducibility": t.get("reproducibility", 0),
            "exploitability": t.get("exploitability", 0),
            "affected_users": t.get("affected_users", 0),
            "discoverability": t.get("discoverability", 0),
            "dread_total": t.get("dread_total", 0),
            "priority": t.get("priority", ""),
            "mitigation": t.get("mitigation", "")[:300],
        })
    threats_json = json.dumps(compact_threats, indent=1, ensure_ascii=False)

    from agentictm.agents.prompt_budget import PromptBudget
    pb = PromptBudget(system_prompt_chars=len(SYSTEM_PROMPT))

    fitted = pb.fit(
        sections={
            "threats": threats_json,
            "system_description": sys_desc_text,
            "components": components_text,
            "data_flows": flows_text,
            "trust_boundaries": boundaries_text,
            "methodology": methodology_sections or "(no methodology reports available)",
            "attack_trees": attack_tree_sections or "(no attack trees generated)",
            "debate": debate_text,
        },
        priorities=[
            "threats", "system_description", "components", "data_flows",
            "trust_boundaries", "methodology", "attack_trees", "debate",
        ],
    )

    return f"""\
# DREAD Validation Request for: {system_name}

## Active Threat Categories: {', '.join(categories)}

---

## 1. Parsed System Description
{fitted["system_description"]}

---

## 2. Architecture

### Components ({len(components)})
{fitted["components"]}

### Data Flows ({len(data_flows)})
{fitted["data_flows"]}

### Trust Boundaries ({len(trust_boundaries)})
{fitted["trust_boundaries"]}

---

## 3. Methodology Analysis Reports (summaries)
{fitted["methodology"]}

---

## 4. Attack Trees (summary)
{fitted["attack_trees"]}

---

## 5. Red Team vs Blue Team Debate (summary)
{fitted["debate"]}

---

## 6. Threats to Validate ({len(threats_final)} threats) — compact summaries
Validate DREAD scores against the system context above.
IMPORTANT: Every input threat MUST appear in your output with its ORIGINAL ID.
Do NOT add new threats, do NOT remove any. Only adjust DREAD scores.
{fitted["threats"]}
"""


def run_dread_validator(
    state: ThreatModelState,
    llm: BaseChatModel,
    config: AgenticTMConfig | None = None,
) -> dict:
    """Nodo de LangGraph: DREAD Validator (Deep Thinker — full-context enriched prompt).

    Lee: threats_final, raw_input, system_description, components, data_flows,
         trust_boundaries, methodology_reports, debate_history
    Escribe: threats_final (overwrite with validated scores)
    """
    threats_final = state.get("threats_final", [])
    if not threats_final:
        logger.info("[DREAD Validator] No threats to validate, skipping")
        return {}

    logger.info("[DREAD Validator] Validating %d threats...", len(threats_final))

    # Self-reflection from config (I02)
    _self_reflect = False
    if config and config.pipeline.self_reflection_enabled and config.pipeline.self_reflection_rounds > 0:
        _self_reflect = True
        logger.info("[DREAD Validator] Self-reflection ENABLED")

    human_prompt = _build_human_prompt(state)

    prompt_kb = len(human_prompt) / 1024
    logger.info("[DREAD Validator] Prompt size: %.1f KB (%d threats)", prompt_kb, len(threats_final))

    # Timeout guard — 600s hard cap (no tools, should be fast)
    DREAD_TIMEOUT = 600
    t0 = time.perf_counter()

    def _run_llm():
        return invoke_agent(
            llm, SYSTEM_PROMPT, human_prompt,
            tools=VALIDATOR_TOOLS,
            agent_name="DREAD Validator",
            enable_self_reflection=_self_reflect,
        )

    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_run_llm)
            response = future.result(timeout=DREAD_TIMEOUT)
    except concurrent.futures.TimeoutError:
        logger.error("[DREAD Validator] TIMEOUT after %ds — keeping original threats", DREAD_TIMEOUT)
        return {}

    elapsed = time.perf_counter() - t0
    logger.info("[DREAD Validator] LLM response (%d chars):\n%s", len(response), response)

    parsed = extract_json_from_response(response)
    if not isinstance(parsed, dict):
        logger.warning("[DREAD Validator] Could not parse response, keeping original threats")
        return {}

    validation_notes = parsed.get("validation_notes", "")
    if validation_notes:
        logger.info("[DREAD Validator] Notes: %s", validation_notes)

    # Index originals by ID so we can merge score updates back into the full threat data.
    orig_by_id = {t.get("id", ""): t for t in threats_final}

    def _clamp(v: int) -> int:
        return max(1, min(10, v))

    # Only accept score updates for threats that ALREADY exist.
    # Reject any new threats the LLM invented.
    score_updates: dict[str, dict] = {}
    new_rejected = 0
    for t in parsed.get("threats", []):
        threat_id = t.get("id", "")
        if threat_id not in orig_by_id:
            new_rejected += 1
            continue
        score_updates[threat_id] = t

    if new_rejected:
        logger.info(
            "[DREAD Validator] Rejected %d new threats invented by LLM (only score updates allowed)",
            new_rejected,
        )

    # Build validated list: start from originals, apply score updates where available.
    validated_threats = []
    for orig in threats_final:
        oid = orig.get("id", "")
        update = score_updates.get(oid)

        if update:
            try:
                d = _clamp(int(update.get("damage", orig.get("damage", 5))))
                r = _clamp(int(update.get("reproducibility", orig.get("reproducibility", 5))))
                e = _clamp(int(update.get("exploitability", orig.get("exploitability", 5))))
                a = _clamp(int(update.get("affected_users", orig.get("affected_users", 5))))
                disc = _clamp(int(update.get("discoverability", orig.get("discoverability", 5))))
            except (TypeError, ValueError):
                d = orig.get("damage", 5)
                r = orig.get("reproducibility", 5)
                e = orig.get("exploitability", 5)
                a = orig.get("affected_users", 5)
                disc = orig.get("discoverability", 5)

            computed_total = d + r + e + a + disc
            final_total = computed_total if computed_total > 0 else int(orig.get("dread_total", 25))

            avg = final_total / 5.0
            if avg >= 9.0:
                priority = "Critical"
            elif avg >= 7.0:
                priority = "High"
            elif avg >= 4.0:
                priority = "Medium"
            else:
                priority = "Low"

            validated = dict(orig)
            validated.update({
                "damage": d,
                "reproducibility": r,
                "exploitability": e,
                "affected_users": a,
                "discoverability": disc,
                "dread_total": final_total,
                "priority": priority,
                "observations": update.get("observations", orig.get("observations", "")),
            })
            validated_threats.append(validated)
        else:
            validated_threats.append(dict(orig))

    if not validated_threats:
        logger.warning("[DREAD Validator] No threats produced, keeping original")
        return {}

    # Sort by DREAD total descending
    validated_threats.sort(key=lambda t: t.get("dread_total", 0), reverse=True)

    # Log changes
    original_count = len(threats_final)
    new_count = len(validated_threats)

    # Count score changes (orig_by_id already built above)
    changes = 0
    for t in validated_threats:
        orig = orig_by_id.get(t["id"])
        if orig and orig.get("dread_total") != t["dread_total"]:
            changes += 1

    total_elapsed = time.perf_counter() - t0
    logger.info(
        "[DREAD Validator] COMPLETED in %.1fs | threats: %d→%d | score changes: %d",
        total_elapsed, original_count, new_count, changes,
    )

    return {
        "threats_final": validated_threats,
    }
